### ISSUE TITLE
Feature request: mouse movement indicator

### ISSUE THREAD

**Issue by Nomad7** [Zergatul/Zergatul.Obs.InputOverlay#5]
NohBoard (https://obsproject.com/forum/resources/nohboard.44/) has a pretty cool feature that shows the direction and amount of mouse movement - any chance a similar indicator could be added here?

They use an outer ring with a dot to indicate angle/direction, and then draw an expanding line out from the center point to indicate velocity, which works pretty well but really any indicator of mouse movement would be great, no specific attachment to NohBoard's particular implementation. :)

Thanks for an awesome plugin by the way, this was by far the easiest to install, run, and configure. Keep up the great work!

**Comment by Zergatul** [comment]
I was thinking about this, but initially didn't find it very useful. Could you attach some video how NohBoard displays mouse movement? I already have few ideas, but it is hard to make them customizable.

**Comment by Nomad7** [comment]
Sure! This is a pretty sloppy example but I think it shows the general idea: https://streamable.com/6o4csq
(I believe this is using one of the GamesLegacy keyboard default templates)

**Comment by Zergatul** [comment]
This is what I got so far: https://streamable.com/mj9910 
However there is a problem with first person view games. Example, when you move mouse to the right to turn right, the game moves cursor to the left, so cursor remains always at the center of game window/screen. I don't know how to distinguish these 2 actions, so I can ignore mouse movements done by game itself, and only count movements done by user.

**Comment by Nomad7** [comment]
Wow awesome, that looks great!

I think NohBoard (or one of the other input overlays I was trying out before I found yours) had an option to track the direction of the mouse relative to the center of the screen - personally that doesn't seem as useful to me?
I feel like the information that would be useful to the viewers is the direction I am currently moving my mouse, which, as far as I can tell from your example, looks like exactly what you're showing. :)

**Comment by Zergatul** [comment]
Tracking direction relative to the center of the screen might solve problem with first person view games, because user moves cursor from the center of the screen, and game put it back to center. My current solution is not working fine in FPV games. You move mouse to the right, game moves it to the left, and overlay highlights both directions.
But what if you run game in window? And center of the screen is not longer the center of game window.

**Comment by Nomad7** [comment]
> You move mouse to the right, game moves it to the left, and overlay highlights both directions

Oh! This didn't click on first read, sorry. Yeah that's definitely not ideal - do all FPS games do that 'move the mouse back' thing? In case it's relevant I'm primarily interested in Team Fortress Classic, a mod for the original Half-Life :)

This is probably too obvious but is there any way to distinguish between the user's movement and the game's movement?

I feel like people likely to show their mouse movements probably aren't playing in windowed mode, but that may be way off base due to my own biases :p

**Comment by Zergatul** [comment]
I didn't find any way to distinguish them with current approach (currently application receives mouse coordinates from Windows, in pixels). I tried to implement one smart algorithm, but it didn't work.

Now I rewrote core module of the application to receive mouse relative movements directly from mouse driver. Now I am getting mouse movements in some units, before Windows or game converts them to pixels. I don't get 'mouse-move-back' movements. But the problem is, these movements from driver are raw, and Windows or games apply some clever algorithms to smooth them, adjust speed, acceleration and so on. When I applied this raw data to existing page I showed above, it just looks bad. I still have a lot of work to do.

**Comment by Nomad7** [comment]
Sorry, I had not expected this request to be quite this challenging! I think you've gotten to a point where I doubt I have any useful advice besides pointing back to NohBoard's implenentation, but if there's anything I can do to help just let me know, happy to do testing or whatever :)

**Comment by Zergatul** [comment]
I also didn't expect this to be this hard. Thanks for help, I will ask you for testing when something will be ready! NohBoard uses quite simple approach, but what's the point to implement same stuff, we need something better :)

**Comment by Zergatul** [comment]
@Nomad7 please check new release. You can contact me in discord if you have any questions: `Zergatul#8135`

**Comment by Nomad7** [comment]
Wow this is awesome! 2.0.0 works essentially perfectly : https://streamable.com/r4e17q

I may adjust the colors and/or intensity thresholds just a tiny bit to be more visible in specific situations for my games, but you've got those clearly identified and easily editable in the mouse-movement.html. I am impressed and 100% satisfied, thank you so much!

**Comment by Zergatul** [comment]
Great!
